version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  build-macos:
    macos:
      xcode: 15.0.0
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - browser-tools/install-chrome
      - gradle/with_cache:
          steps:
            - run:
                name: build
                command: ./gradlew check
      - gradle/collect_test_results
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -D -o $HOME/secring.gpg
              ./gradlew dokkaJavadocCommonJar
              ./gradlew publish -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId="$MAVEN_CENTRAL_KEY_ID" -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
workflows:
  version: 2
  build:
    jobs:
      - build-macos:
          filters:
            branches:
              ignore: main
      - build-macos:
          context: opensource-maven
          filters:
            branches:
              only: main